services:
  - type: web
    name: saferide-backend
    env: node
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: saferide-frontend
          envVar: RENDER_EXTERNAL_URL

  - type: web
    name: saferide-frontend
    env: static
    buildCommand: npm install --prefix reacat-frontend && npm run build --prefix reacat-frontend
    staticPublishPath: ./reacat-frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: saferide-backend
          envVar: RENDER_EXTERNAL_URL
